language: python
sudo: required

services:
  - docker

python:
  - '3.6'

before_install:
  - pip install --upgrade pip

install:
  - pip install --upgrade setuptools
  - pip install -r requirement-dev.txt

cache: pip

script:
  - pytest
